/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conexion.Cliente;

/**
 *
 * @author Invitado
 */
public class MainForm extends javax.swing.JFrame implements GUIObserver{

    private final Cliente clienteServer;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.clienteServer=new Cliente(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTextoEnviar = new javax.swing.JTextField();
        lblInstruccion = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        lblInstruccion1 = new javax.swing.JLabel();
        lblTituloRecibido = new javax.swing.JLabel();
        txtRecibido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTextoEnviar.setText("204270,ALFONSO,ISW");

        lblInstruccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblInstruccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccion.setText("Sistema Alumno");

        btnEnviar.setText("Enviar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblInstruccion1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblInstruccion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccion1.setText("Texto plano a enviar (lo del alumno se manda con comas): ");

        lblTituloRecibido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloRecibido.setText("Recibido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInstruccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInstruccion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtTextoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnviar)
                        .addGap(305, 305, 305))))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloRecibido))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstruccion)
                .addGap(11, 11, 11)
                .addComponent(lblInstruccion1)
                .addGap(18, 18, 18)
                .addComponent(txtTextoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnviar)
                .addGap(38, 38, 38)
                .addComponent(lblTituloRecibido)
                .addGap(18, 18, 18)
                .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        txtRecibido.setText("Esperando al servidor...");
        btnEnviar.setEnabled(false);
        clienteServer.enviar(txtTextoEnviar.getText());
    }//GEN-LAST:event_btnEnviarMouseClicked

    @Override
    public void update(String contenido) {
        btnEnviar.setEnabled(true);
        txtRecibido.setText(contenido);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblInstruccion1;
    private javax.swing.JLabel lblTituloRecibido;
    private javax.swing.JTextField txtRecibido;
    private javax.swing.JTextField txtTextoEnviar;
    // End of variables declaration//GEN-END:variables
}
