/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alumno;

/**
 *
 * @author laura
 */
public class FrmAlumno extends javax.swing.JFrame {

    /**
     * Creates new form FrmAlumno
     */
    public FrmAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 173, 37));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 228, -1));
        getContentPane().add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 228, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 228, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblID.setText("ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 28, -1));

        lblNombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreCompleto.setText("NOMBRE COMPLETO");
        getContentPane().add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        lblCarrera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCarrera.setText("CARRERA");
        getContentPane().add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        lblAlumno.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblAlumno.setText("Solictar Kardex");
        getContentPane().add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
